#!/usr/bin/env python3
"""Regenerate the section index at the top of docs/CONTRACTS.md.

Why: the file is 3,200+ lines and ~245 KB, and every worker brief cites one or
two of its sections. Read whole it costs ~80k tokens of context that is then
re-sent on every later request; located and read by range it costs ~2-3k. The
index is what makes the cheap path the obvious one.

Run after any pass that adds, removes or renames a section:

    py -3.14 staging/contracts_index.py          # Windows
    python3 staging/contracts_index.py           # Linux

The block between the markers is the only thing touched. Line numbers describe
the file *after* the write, so the script re-runs its own maths until the
published ranges stop moving (a section count change shifts the block by one
line; that converges on the second pass).
"""

from __future__ import annotations

import pathlib
import re
import sys

CONTRACTS = pathlib.Path(__file__).resolve().parent.parent / "docs" / "CONTRACTS.md"
START = "<!-- section-index:start -->"
END = "<!-- section-index:end -->"
HEADING = re.compile(r"^## (§[^\s—(]+)\s*(.*)$")

INTRO = [
    START,
    "**Read by range, not whole.** This index is generated by",
    "`staging/contracts_index.py`; do not hand-edit it. To find a section:",
    "",
    "```bash",
    "rg -n '^## §' docs/CONTRACTS.md    # heading -> line number",
    "```",
    "",
    "then read only that range (`view --offset <line-1> --limit <span>`). Reading",
    "the whole file costs ~80k tokens and every tool result is re-sent on each",
    "later request; one section costs ~2-3k.",
    "",
]


def sections(lines: list[str]) -> list[tuple[int, str, str]]:
    """(0-based index, label, title) for every '## §N …' heading."""
    found = []
    for i, line in enumerate(lines):
        m = HEADING.match(line)
        if m:
            title = m.group(2).strip()
            title = title.split("`")[0].strip(" —-–") or title
            found.append((i, m.group(1), title))
    return found


def build(lines: list[str]) -> list[str]:
    """The index block, with ranges valid for `lines` as given."""
    heads = sections(lines)
    rows = ["| Section | Topic | Lines |", "|---|---|---|"]
    for n, (idx, label, title) in enumerate(heads):
        end = (heads[n + 1][0] - 1) if n + 1 < len(heads) else len(lines) - 1
        title = (title[:68] + "…") if len(title) > 69 else title
        rows.append(f"| {label} | {title} | L{idx + 1}–L{end + 1} |")
    return INTRO + rows + ["", END]


def splice(lines: list[str], block: list[str]) -> list[str]:
    if START in lines and END in lines:
        a, b = lines.index(START), lines.index(END)
        return lines[:a] + block + lines[b + 1 :]
    # First run: place the block after the intro, before the first section.
    at = sections(lines)[0][0]
    while at > 0 and not lines[at - 1].strip():
        at -= 1
    return lines[:at] + block + [""] + lines[at:]


def main() -> int:
    text = CONTRACTS.read_text(encoding="utf-8")
    lines = text.split("\n")

    for _ in range(4):
        candidate = splice(lines, build(lines))
        if candidate == lines:
            break
        lines = candidate
    else:
        print("index did not converge — aborting without writing", file=sys.stderr)
        return 1

    new = "\n".join(lines)
    if new == text:
        print("index already current")
        return 0
    CONTRACTS.write_text(new, encoding="utf-8")
    heads = sections(lines)
    print(f"index written: {len(heads)} sections, {len(lines)} lines total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
