#!/usr/bin/env python3
"""Regenerate the section index at the top of the big spec docs.

Why: a spec over ~400 lines costs 10-30k tokens read whole and every token is
re-sent on each later request; the one section a task needs costs a fraction of
that. The index (label -> line range) makes the cheap path the obvious one, the
same mechanism `staging/contracts_index.py` applies to docs/CONTRACTS.md.

Usage (run after any pass that adds, removes or renames a section):

    python3 staging/docs_index.py                 # Linux: the default nine specs
    py -3.14 staging/docs_index.py                # Windows
    python3 staging/docs_index.py docs/design/FX_SPEC.md path/to/other.md

Only the block between the markers is touched. Line numbers describe the file
*after* the write, so the script re-runs its own maths until the published
ranges stop moving (a section count change shifts the block; that converges on
the second pass). A file whose headings do not match the numbered/lettered/
S-numbered forms is skipped with a warning.

docs/gameplay/18_engine_spec.md is owner-locked and deliberately absent from
the default list: never index it without the owner's word.
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

DEFAULT_TARGETS = [
    "docs/design/STATION_HUB.md",
    "docs/design/MAIN_MENU_V2.md",
    "docs/design/UI_SPEC.md",
    "docs/design/IMPLEMENTATION_PLAN.md",
    "docs/gameplay/09_ship_slots_modules.md",
    "docs/design/ICONS_SPEC.md",
    "docs/design/ASSET_AUDIT.md",
    "docs/design/AUDIO_SPEC.md",
    "docs/design/MENU_FLOW.md",
]

START = "<!-- section-index:start -->"
END = "<!-- section-index:end -->"
HEADING = re.compile(r"^## ([0-9A-Za-z]+[.]|[§][^\s—(]+)\s*(.*)$")


def intro(rel: str) -> list[str]:
    return [
        START,
        "**Read by range, not whole.** This index is generated by",
        "`staging/docs_index.py`; do not hand-edit it. To find a section:",
        "",
        "```bash",
        f"rg -n '^## ' {rel}    # heading -> line number",
        "```",
        "",
        "then read only that range (`view --offset <line-1> --limit <span>`).",
        "The whole file costs far more than the one section your task needs,",
        "and every tool result is re-sent on each later request.",
        "",
    ]


def sections(lines: list[str]) -> list[tuple[int, str, str]]:
    """(0-based index, label, title) for every matched '## …' heading."""
    found = []
    for i, line in enumerate(lines):
        m = HEADING.match(line)
        if m:
            title = m.group(2).strip()
            title = title.split("`")[0].strip(" —-–") or title
            found.append((i, m.group(1), title))
    return found


def build(lines: list[str], rel: str) -> list[str]:
    """The index block, with ranges valid for `lines` as given."""
    heads = sections(lines)
    rows = ["| Section | Topic | Lines |", "|---|---|---|"]
    for n, (idx, label, title) in enumerate(heads):
        end = (heads[n + 1][0] - 1) if n + 1 < len(heads) else len(lines) - 1
        title = (title[:68] + "…") if len(title) > 69 else title
        rows.append(f"| {label} | {title} | L{idx + 1}–L{end + 1} |")
    return intro(rel) + rows + ["", END]


def splice(lines: list[str], block: list[str]) -> list[str]:
    if START in lines and END in lines:
        a, b = lines.index(START), lines.index(END)
        return lines[:a] + block + lines[b + 1 :]
    # First run: place the block after the intro, before the first section.
    at = sections(lines)[0][0]
    while at > 0 and not lines[at - 1].strip():
        at -= 1
    return lines[:at] + block + [""] + lines[at:]


def index_file(path: pathlib.Path) -> int:
    rel = path.relative_to(ROOT).as_posix()
    text = path.read_bytes().decode("utf-8")
    eol = "\r\n" if "\r\n" in text else "\n"
    lines = text.replace("\r\n", "\n").split("\n")

    if not sections(lines):
        print(f"skipped (no numbered/lettered sections): {rel}", file=sys.stderr)
        return 1

    for _ in range(4):
        candidate = splice(lines, build(lines, rel))
        if candidate == lines:
            break
        lines = candidate
    else:
        print(f"{rel}: index did not converge — aborting without writing",
              file=sys.stderr)
        return 1

    new = "\n".join(lines)
    if new == text.replace("\r\n", "\n"):
        print(f"{rel}: index already current")
        return 0
    path.write_bytes(new.replace("\n", eol).encode("utf-8"))
    heads = sections(lines)
    print(f"{rel}: index written, {len(heads)} sections, {len(lines)} lines")
    return 0


def main() -> int:
    targets = sys.argv[1:] or DEFAULT_TARGETS
    status = 0
    for t in targets:
        path = (ROOT / t).resolve() if not pathlib.Path(t).is_absolute() else pathlib.Path(t)
        if not path.exists():
            print(f"missing: {t}", file=sys.stderr)
            status = 1
            continue
        status |= index_file(path)
    return status


if __name__ == "__main__":
    sys.exit(main())
