"""Ship the D6 cockpit-instrument masters into the Godot project.

The Phase G lane order is: render -> `panels.py --detect` -> cut each object -> key each cut on
its own -> trim and centre (`refit_panels.py`). This step takes those trimmed cuts and puts them
on their shipped boxes:

* every `ui_*` cut is fitted **contain** on its master box and centred (the D2 ruling: one master
  per sprite at 2x its logical box, no `@2x` files, no size-variant families). `--fit contain` is
  the ICONS_SPEC section 9.6 law; stretching a round dial to fill a square box is not an option.
* `ui_cockpit_frame` is rebuilt as a nine-slice at an exact 64 px band (`reband_frame.py`, the
  F.2 C1 recipe): the painted band must equal the nine-slice margin, whatever the model drew.
* the four panel renders ship as provenance panels under `assets/icons/` (`panel_` family,
  ASSET_NAMING_SPEC section 2), the raw 2048x2048 RGB sheet each family of cells was cut from.

The generation log is written beside the shipped family from the same run records (AGENTS.md: AI
art is not CC0).

Usage:
    py -3.14 staging/phase_g/ship_d6.py --list
    py -3.14 staging/phase_g/ship_d6.py --stage-only     # masters into staging/phase_g/ui/_masters
    py -3.14 staging/phase_g/ship_d6.py                  # + copy into the project
    py -3.14 staging/phase_g/ship_d6.py --replace
"""
from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from pathlib import Path

import numpy as np
from PIL import Image

import wave_g

ROOT = Path(__file__).resolve().parents[2]
STAGE = wave_g.STAGE
ASSETS = ROOT / "vajb-orbit" / "assets"
MASTERS = STAGE / "ui" / "_masters"
sys.path.insert(0, str(ROOT / "staging" / "phase_f"))
import reband_frame  # noqa: E402  (the F.2 C1 nine-slice rebuild)

UI_RUNS = ("panel_instruments", "panel_frame_glass", "panel_sevenseg_a", "panel_sevenseg_b")
FRAME = "ui_cockpit_frame"
FRAME_BAND_DIVISOR = 3
## A shaped object cut from a render keeps its aspect on its master box (stretching a disc or a
## triangle is not an option).
FIT_CONTAIN = ("ui_compass_rose", "ui_compass_lubber")
SEG_CELLS = tuple(f"ui_seg_{i}" for i in range(10)) + ("ui_seg_pct", "ui_seg_blank")
## Masters that are not a plain cut of a render: they are prepared at their shipped box by the
## step named here (and re-measured by it), so ship_d6 copies them instead of re-fitting them.
PREPARED = {
    "ui_cockpit_frame": "nine-slice rebuild, `ui_authored.py`",
    "ui_gauge_face": "needle wiped, `gauge_clean.py`",
    "ui_gauge_needle": "authored SVG, `ui_authored.py`",
    "ui_readout_glass": "authored SVG, `ui_authored.py`",
}
for _cell in SEG_CELLS:
    PREPARED[_cell] = "authored SVG segments, `seg_svg_digits.py`"
## The two cells the panels never produced; `ui_authored.py` writes them, and they are logged
## against the panel that was ordered to deliver them.
EXTRA = (("panel_instruments", "ui_gauge_needle"),
         ("panel_frame_glass", "ui_readout_glass"))
LOG_HEAD = (
    "# D6 cockpit instruments - generation log\n\n"
    "**Generated by `staging/phase_g/ship_d6.py` from the Phase G lane. Never hand-edit.**\n\n"
    "Model: `gpt-image-2-5-flare-text-to-image` (`flare`), 2K, aspect 1:1, opaque render on a "
    "plain solid pure white background (UI_CHROME_ASSETS_SPEC section 1.2). Style law: "
    "`vajb-orbit/assets/style-block.txt` passed verbatim as the prompt preamble. Work order: "
    "UI_CHROME_ASSETS_SPEC section 11 (wave D6); per-run prompts are that section's verbatim "
    "text plus section 8's negative list.\n"
    "Alpha: each panel object is cut out of the render on its own box, keyed on its own through "
    "`recraft/remove-background` (`staging/phase_g/key_new.py`), then trimmed and centred "
    "(`staging/phase_g/refit_panels.py`); a panel is never keyed whole. Masters ship at 2x their "
    "logical box (section 11's table).\n"
    "Six files are not a plain cut because the render could not deliver them (three attempts "
    "each); the Route column names the step, and the D6-M0 report carries the measurements.\n"
    "AI-generated art is not CC0 (AGENTS.md).\n\n"
    "| File | Panel | Panel cell | Job | Box | Route | Prompt |\n|---|---|---|---|---|---|---|\n")


def md5(path: Path) -> str:
    return hashlib.md5(path.read_bytes()).hexdigest()


def job_of(path: Path) -> str:
    job = path.with_name(f"{path.stem}.job.json")
    if not job.exists():
        return "-"
    import json
    return str(json.loads(job.read_text(encoding="utf-8")).get("task_id", "-"))


def fit_contain(img: Image.Image, box: tuple[int, int]) -> Image.Image:
    """Scale to fit the box, keep the aspect, centre on a transparent canvas of the box."""
    width, height = img.size
    target_w, target_h = box
    scale = min(target_w / width, target_h / height)
    new = (max(1, int(round(width * scale))), max(1, int(round(height * scale))))
    scaled = img.convert("RGBA").resize(new, Image.LANCZOS)
    canvas = Image.new("RGBA", box, (0, 0, 0, 0))
    canvas.paste(scaled, ((target_w - new[0]) // 2, (target_h - new[1]) // 2))
    return clean_alpha(canvas)


def clean_alpha(img: Image.Image, floor: int = 8) -> Image.Image:
    """Drop the near-transparent fringe a resize leaves, so the keyed edge stays hard."""
    pixels = np.asarray(img).copy()
    pixels[..., 3] = np.where(pixels[..., 3] < floor, 0, pixels[..., 3])
    return Image.fromarray(pixels, "RGBA")


def fit_fill(img: Image.Image, box: tuple[int, int]) -> Image.Image:
    """Scale to the exact box (flat plates only: the plate must fill the logical cell)."""
    return clean_alpha(img.convert("RGBA").resize(box, Image.LANCZOS))


def measure(path: Path) -> dict:
    """The per-file numbers the report carries: box, transparency, ink, bytes, md5."""
    img = Image.open(path).convert("RGBA")
    alpha = np.asarray(img.getchannel("A"))
    return {"pixels": list(img.size), "bytes": path.stat().st_size, "md5": md5(path),
            "transparent_pct": round(100.0 * float((alpha == 0).mean()), 2),
            "ink_pct": round(100.0 * float((alpha > 8).mean()), 2)}


def plan(only: tuple[str, ...] = ()) -> list[tuple[str, str, Path | None]]:
    """(panel run, name, source cut) for every shipped cell, optionally narrowed to some runs.

    The last two entries are the cells the panels never produced (three renders each): they belong
    to their ordering panel for the log, but have no cut of their own - `ui_authored.py` writes the
    master directly.
    """
    rows: list[tuple[str, str, Path | None]] = []
    for run_id in UI_RUNS:
        if only and run_id not in only and not any(n in only for _i, n, _r in wave_g.RUNS[run_id]["cells"]):
            continue
        spec = wave_g.RUNS[run_id]
        for _index, name, _rotate in spec["cells"]:
            if only and name not in only and run_id not in only:
                continue
            rows.append((run_id, name, STAGE / "ui" / f"{name}.png"))
    for run_id, name in EXTRA:
        if only and name not in only and run_id not in only:
            continue
        rows.append((run_id, name, None))
    return rows


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--stage-only", action="store_true")
    parser.add_argument("--replace", action="store_true")
    parser.add_argument("--only", nargs="*", default=[],
                        help="narrow to run ids and/or master names (staging + ship)")
    args = parser.parse_args()

    rows = plan(tuple(args.only))
    missing = [name for _r, name, path in rows if path is not None and not path.is_file()]
    if missing:
        print(f"missing cut(s) in staging/phase_g/ui: {', '.join(missing)}")
        return 1
    MASTERS.mkdir(parents=True, exist_ok=True)

    report: dict = {}
    log_rows: list[str] = []
    for run_id, name, path in rows:
        spec = wave_g.RUNS[run_id]
        box = spec["boxes"][name]
        if name in PREPARED:
            ## Prepared at its shipped box by its own step (segments, frame, needle, glass, wiped
            ## face); shipping copies it and checks the box rather than re-fitting it.
            master = Image.open(MASTERS / f"{name}.png").convert("RGBA")
            if master.size != box:
                print(f"{name}: prepared master is {master.size}, expected {box[0]}x{box[1]}")
                return 1
            report[name] = {"box": list(box), "route": PREPARED[name]}
        else:
            before = Image.open(path).size
            fit = fit_contain if name in FIT_CONTAIN else fit_fill
            master = fit(Image.open(path), box)
            report[name] = {"box": list(box), "cut_box": list(before),
                            "route": "recraft-keyed render cut, "
                                     + ("contain" if name in FIT_CONTAIN else "fill") + " fit"}
            master.save(MASTERS / f"{name}.png")
        cell = [i for i, n, _r in spec["cells"] if n == name]
        cell_label = f"{cell[0]} of {len(spec['cells'])}" if cell else (name if name in ("ui_gauge_needle", "ui_readout_glass") else "-")
        ## The panel's own job id is the provenance for every cell: `refit_panels.py` writes the
        ## cut, not a job, and the render that produced it is the panel render.
        job = job_of(STAGE / "ui" / f"{spec['panel_name']}.png")
        log_rows.append(f"| `{name}.png` | `{spec['panel_name']}` | {cell_label} | "
                        f"{job} | {box[0]}x{box[1]} | "
                        f"{report[name]['route']} | "
                        f"{spec['subject'].splitlines()[0][:110]}... |")
        print(f"{name:18s} {path.name if path else '-':26s} "
              f"{str(report[name].get('cut_box', '-')):12s} -> "
              f"{master.size[0]}x{master.size[1]}  {report[name]['route']}")

    if args.list:
        print(f"{len(rows)} master(s) staged in {MASTERS.relative_to(ROOT)}")
        return 0

    if not args.stage_only:
        ui_dir = ASSETS / "ui"
        icons_dir = ASSETS / "icons"
        blocked = 0
        for _run_id, name, _path in rows:
            target = ui_dir / f"{name}.png"
            if target.exists() and md5(target) != md5(MASTERS / f"{name}.png") and not args.replace:
                print(f"SKIP {name}: exists in the project with different bytes (--replace)")
                blocked += 1
                continue
            ui_dir.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(MASTERS / f"{name}.png", target)
        for panel in wave_g.RUNS:
            spec = wave_g.RUNS[panel]
            if spec["family"] != "ui" or panel not in {r for r, _n, _p in rows}:
                continue
            if spec.get("panel_name") not in ("panel_instruments", "panel_frame_glass",
                                              "panel_sevenseg_a", "panel_sevenseg_b"):
                continue
            source = STAGE / "ui" / f"{spec['panel_name']}.png"
            target = icons_dir / f"{spec['panel_name']}.png"
            if not source.is_file():
                print(f"SKIP panel {spec['panel_name']}: no render in staging")
                blocked += 1
                continue
            icons_dir.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
            print(f"panel {spec['panel_name']}.png -> assets/icons/ "
                  f"({Image.open(source).size[0]}x{Image.open(source).size[1]})")
        (ASSETS / "ui" / "generation_log_d6.md").write_text(
            LOG_HEAD + "\n".join(log_rows) + "\n", encoding="utf-8")
        print(f"shipped {len(rows)} master(s); log assets/ui/generation_log_d6.md")
        if blocked:
            print(f"{blocked} file(s) refused")
        import json
        for report_name, entry in report.items():
            entry.update(measure(MASTERS / f"{report_name}.png"))
        (STAGE / "ui" / "ship_report.json").write_text(json.dumps(report, indent=1),
                                                        encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
