"""Ship the D7 cockpit-panel-family masters into the Godot project.

Wave D7, `docs/design/UI_CHROME_ASSETS_SPEC.md` section 12. The Phase G lane order is:
render -> `panels.py --detect` -> cut each object on its own box -> key each cut on its own ->
trim and centre (`refit_panels.py`). This step puts those trimmed cuts on their shipped boxes.

* every D7 cut is fitted **contain** on its master box and centred. Section 12 pins the master for
  `ui_cockpit_panel` (928x512), `ui_gauge_face` (240x240) and `ui_status_panel` (1440x1040); the
  two armory boxes are the measured ones recorded in `wave_g.py`'s D7 section.
* the five panel renders ship as provenance panels under `assets/icons/` (`panel_` family,
  ASSET_NAMING_SPEC section 2) - the whole 2048x2048 sheet each family of cells was cut from.
* the generation log is written beside the shipped family from the same run records (AGENTS.md:
  AI art is not CC0).

`ui_gauge_face` already exists in the project (the D6 face); section 12's run 2 is a re-cut under
the same name, so this step needs `--replace` for it. `ui_seg_*`, `ui_compass_*` and
`ui_gauge_needle` are not in the D7 plan and stay byte-identical.

Usage:
    py -3.14 staging/phase_g/ship_d7.py --list
    py -3.14 staging/phase_g/ship_d7.py --stage-only     # masters into staging/phase_g/ui/_masters
    py -3.14 staging/phase_g/ship_d7.py                  # + copy into the project
    py -3.14 staging/phase_g/ship_d7.py --replace
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path

import numpy as np
from PIL import Image

import wave_g

ROOT = Path(__file__).resolve().parents[2]
STAGE = wave_g.STAGE
ASSETS = ROOT / "vajb-orbit" / "assets"
MASTERS = STAGE / "ui" / "_masters"

D7_RUNS = ("panel_cockpit", "panel_gauge", "panel_armory_console", "panel_armory_plates",
           "panel_status")
## Wave D7-A1/A2, UI_CHROME_ASSETS_SPEC section 12 Amendment 2: the three console panels are
## re-rendered as flat painted plates (their wells are code-drawn at the pinned rects), and those
## plates supersede A0's well-bearing masters for the same three names. They head the plan so each
## name ships once, from the newest cut. D7-A2 re-renders the armory console on the canvas UI_SPEC
## section 3.10's Amendment 2 rules (872x956 -> 1744x1912) and heads the console name.
FLAT_RUNS = ("panel_armory_console_flat_a2", "panel_cockpit_flat", "panel_armory_console_flat",
             "panel_status_flat")
A1_RUNS = FLAT_RUNS
PLAN_RUNS = FLAT_RUNS + D7_RUNS
## The five renders' provenance panels under `assets/icons/`. ASSET_NAMING_SPEC section 12 names
## three of them (`panel_cockpit`, `panel_armory`, `panel_status`); the gauge re-cut and the
## two-cell plates render take derived `panel_` names under section 1's grammar (the D6
## precedent: `panel_instruments` / `panel_frame_glass` were derived the same way).
PANEL_NAMES = {
    "panel_cockpit": "panel_cockpit",
    "panel_gauge": "panel_gauge",
    "panel_armory_console": "panel_armory",
    "panel_armory_plates": "panel_armory_plates",
    "panel_status": "panel_status",
}
## The flat re-renders provide the provenance for the three names they supersede: the shipped art is
## the flat plate, so the whole render it was cut from is the provenance panel. The console's
## provenance comes from the D7-A2 re-render (it heads `PLAN_RUNS`).
PANEL_NAMES_A1 = {
    "panel_armory_console_flat_a2": "panel_armory",
    "panel_cockpit_flat": "panel_cockpit",
    "panel_armory_console_flat": "panel_armory",
    "panel_status_flat": "panel_status",
}
LOG_HEAD = (
    "# D7 cockpit panel family - generation log\n\n"
    "**Generated by `staging/phase_g/ship_d7.py` from the Phase G lane. Never hand-edit.**\n\n"
    "Model: `gpt-image-2-5-flare-text-to-image` (`flare`), 2K (explicit aspect; 1:1 unless a run "
    "pins the box's own), opaque render on a plain solid pure white background "
    "(UI_CHROME_ASSETS_SPEC section 1.2). Style law: "
    "`vajb-orbit/assets/style-block.txt` passed verbatim as the prompt preamble (section 12's "
    "route, the section 11 route: preamble, not --style-file). Work order: UI_CHROME_ASSETS_SPEC "
    "section 12 (wave D7); per-run prompts are that section's verbatim text preceded by its "
    "framing sentence and followed by section 8's negative list.\n"
    "Alpha: each panel object is cut out of the render on its own box, keyed on its own through "
    "`recraft/remove-background` (`staging/phase_g/key_new.py`), then trimmed and centred "
    "(`staging/phase_g/refit_panels.py`); a panel is never keyed whole.\n"
    "UI_CHROME_ASSETS_SPEC section 12 Amendment 2 (wave D7-A1, console re-rendered by D7-A2): "
    "`ui_cockpit_panel`, `ui_armory_console` and `ui_status_panel` are **flat painted plates** - "
    "their per-run prompts drop every `recessed well` phrase and the wells are code-drawn recesses "
    "at the pinned rects, so the plate is the whole surface the pinned box mounts. Their cuts ship "
    "with the lane's trim pad at 0 (floored at 8 px) and, for the armory console and the status "
    "panel, a render canvas at the pinned box's own aspect. `ui_armory_console` rides the canvas "
    "UI_SPEC section 3.10's Amendment 2 rules (872x956 at 1x -> 1744x1912; the D7-R1 MED-1 ruling). "
    "`ui_gauge_face`, `ui_armory_rack_plate` and "
    "`ui_armory_row_plate` are A0's bytes.\n"
    "AI-generated art is not CC0 (AGENTS.md).\n\n"
    "| File | Panel | Panel cell | Job | Box | Route | Prompt |\n|---|---|---|---|---|---|---|\n")


def md5(path: Path) -> str:
    return hashlib.md5(path.read_bytes()).hexdigest()


def job_of(path: Path) -> str:
    job = path.with_name(f"{path.stem}.job.json")
    if not job.exists():
        return "-"
    return str(json.loads(job.read_text(encoding="utf-8")).get("task_id", "-"))


def clean_alpha(img: Image.Image, floor: int = 8) -> Image.Image:
    """Drop the near-transparent fringe a resize leaves, so the keyed edge stays hard."""
    pixels = np.asarray(img).copy()
    pixels[..., 3] = np.where(pixels[..., 3] < floor, 0, pixels[..., 3])
    return Image.fromarray(pixels, "RGBA")


def fit_contain(img: Image.Image, box: tuple[int, int]) -> Image.Image:
    """Scale to fit the box, keep the aspect, centre on a transparent canvas of the box."""
    width, height = img.size
    target_w, target_h = box
    scale = min(target_w / width, target_h / height)
    new = (max(1, int(round(width * scale))), max(1, int(round(height * scale))))
    scaled = img.convert("RGBA").resize(new, Image.LANCZOS)
    canvas = Image.new("RGBA", box, (0, 0, 0, 0))
    canvas.paste(scaled, ((target_w - new[0]) // 2, (target_h - new[1]) // 2))
    return clean_alpha(canvas)


def measure(path: Path) -> dict:
    """The per-file numbers the report carries: box, transparency, ink, bytes, md5."""
    img = Image.open(path).convert("RGBA")
    alpha = np.asarray(img.getchannel("A"))
    return {"pixels": list(img.size), "bytes": path.stat().st_size, "md5": md5(path),
            "transparent_pct": round(100.0 * float((alpha == 0).mean()), 2),
            "ink_pct": round(100.0 * float((alpha > 8).mean()), 2)}


def plan(only: tuple[str, ...] = ()) -> list[tuple[str, str, Path]]:
    """Every master to ship, one row per name: the A1 flat plates claim their name first.

    `only` scopes the copy, never the log - the generation log stays the record of the whole
    family even when one pass ships a subset.
    """
    rows: list[tuple[str, str, Path]] = []
    claimed: set[str] = set()
    for run_id in PLAN_RUNS:
        spec = wave_g.RUNS[run_id]
        for _index, name, _rotate in spec["cells"]:
            if name in claimed:
                continue
            claimed.add(name)
            rows.append((run_id, name, STAGE / "ui" / f"{name}.png"))
    if only:
        rows = [row for row in rows
                if row[1] in only or row[0] in only
                or any(n in only for _i, n, _r in wave_g.RUNS[row[0]]["cells"])]
    return rows


def panel_plan(only: tuple[str, ...] = ()) -> list[tuple[str, str]]:
    """(shipped panel name, run id providing the render) - the A1 re-render wins its three names."""
    sources: dict[str, str] = {}
    for run_id in PLAN_RUNS:
        for table in (PANEL_NAMES_A1, PANEL_NAMES):
            if run_id in table:
                sources.setdefault(table[run_id], run_id)
    rows = sorted(sources.items())
    if only:
        rows = [row for row in rows
                if row[1] in only
                or any(n in only for _i, n, _r in wave_g.RUNS[row[1]]["cells"])]
    return rows


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--stage-only", action="store_true")
    parser.add_argument("--replace", action="store_true")
    parser.add_argument("--only", nargs="*", default=[])
    args = parser.parse_args()

    rows = plan(tuple(args.only))
    all_rows = plan()
    missing = [name for _r, name, path in rows if not path.is_file()]
    if missing:
        print(f"missing cut(s) in staging/phase_g/ui: {', '.join(missing)}")
        return 1
    MASTERS.mkdir(parents=True, exist_ok=True)

    report: dict = {}
    log_rows: list[str] = []
    ## The masters are staged for the whole family (the log is the record of all six), while
    ## `--only` scopes which of them are copied into the project.
    for run_id, name, path in all_rows:
        spec = wave_g.RUNS[run_id]
        box = spec["boxes"][name]
        before = Image.open(path).size
        master = fit_contain(Image.open(path), box)
        route = ("recraft-keyed render cut, contain fit"
                 if run_id in D7_RUNS and run_id not in A1_RUNS else
                 f"recraft-keyed flat plate cut, contain fit, pad "
                 f"{spec.get('pad_share', 0.04):.2f}, canvas {spec.get('aspect', '1:1')} "
                 f"(Amendment 2)")
        report[name] = {"box": list(box), "cut_box": list(before), "route": route}
        master.save(MASTERS / f"{name}.png")
        cell = [i for i, n, _r in spec["cells"] if n == name]
        cell_label = f"{cell[0]} of {len(spec['cells'])}" if cell else "-"
        job = job_of(STAGE / "ui" / f"{spec['panel_name']}.png")
        log_rows.append(f"| `{name}.png` | `{spec['panel_name']}` | {cell_label} | "
                        f"{job} | {box[0]}x{box[1]} | "
                        f"{route} | "
                        f"{spec['subject'].splitlines()[0][-110:]} |")
        print(f"{name:22s} {path.name:26s} {str(before):12s} -> "
              f"{master.size[0]}x{master.size[1]}  {route}")

    if args.list:
        print(f"{len(rows)} master(s) staged in {MASTERS.relative_to(ROOT)}")
        return 0

    if not args.stage_only:
        ui_dir = ASSETS / "ui"
        icons_dir = ASSETS / "icons"
        blocked = 0
        for _run_id, name, _path in rows:
            target = ui_dir / f"{name}.png"
            if (target.exists() and md5(target) != md5(MASTERS / f"{name}.png")
                    and not args.replace):
                print(f"SKIP {name}: exists in the project with different bytes (--replace)")
                blocked += 1
                continue
            ui_dir.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(MASTERS / f"{name}.png", target)
            print(f"  shipped {name}.png -> assets/ui/")
        for panel_name, run_id in panel_plan(tuple(args.only)):
            source = STAGE / "ui" / f"{wave_g.RUNS[run_id]['panel_name']}.png"
            target = icons_dir / f"{panel_name}.png"
            if not source.is_file():
                print(f"SKIP panel {panel_name}: no render in staging")
                blocked += 1
                continue
            icons_dir.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
            print(f"panel {panel_name}.png -> assets/icons/ "
                  f"({Image.open(source).size[0]}x{Image.open(source).size[1]})")
        (ASSETS / "ui" / "generation_log_d7.md").write_text(
            LOG_HEAD + "\n".join(log_rows) + "\n", encoding="utf-8")
        print(f"staged {len(report)} master(s), shipped {len(rows)}; "
              f"log assets/ui/generation_log_d7.md")
        if blocked:
            print(f"{blocked} file(s) refused")
        for report_name, entry in report.items():
            entry.update(measure(MASTERS / f"{report_name}.png"))
        (STAGE / "ui" / "ship_report_d7.json").write_text(json.dumps(report, indent=1),
                                                          encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
