"""Ship the approved Phase G lane into the Godot project.

Copies the renders a run is allowed to ship (`review_only` runs stay in `staging/phase_g/` until
the owner approves them) into `vajb-orbit/assets/<family>/`, and writes the family's Phase G
generation log next to them from the same run records, so the prompt, model and job id that
produced each shipped file are on disk beside it (AGENTS.md: AI art is not CC0).

A file whose name already exists in the project is refused unless its bytes are identical: a
silent overwrite of shipped art is indistinguishable from art that never changed.

Usage:
    py -3.14 staging/phase_g/ship_batch_g.py --list
    py -3.14 staging/phase_g/ship_batch_g.py ships fx
    py -3.14 staging/phase_g/ship_batch_g.py fx --replace
"""
from __future__ import annotations

import argparse
import hashlib
import shutil
from pathlib import Path

import wave_g

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "vajb-orbit" / "assets"
LOG_HEAD = (
    "# Phase G - shipped assets\n\n"
    "**Regenerated by `staging/phase_g/ship_batch_g.py`. Never hand-edit.**\n\n"
    "Model: `gpt-image-2-5-flare-text-to-image` (`flare`), 2K, aspect 1:1. "
    "Style law: `docs/design/STYLE_BIBLE.md` section 9 (human) and section 9.1 (alien addendum), "
    "passed verbatim as the prompt preamble. Work order: `.agents/gen/dispatch_designer.md`; "
    "FX inventory: `docs/design/FX_SPEC.md` section 7.2.\n"
    "Alpha: see each row - ships are keyed through `recraft/remove-background` "
    "(`staging/phase_g/key_new.py`); FX stay RGB on void black and are never keyed "
    "(FX_SPEC section 0.1).\n\n"
    "| File | Run | Job | Alpha | Prompt |\n|---|---|---|---|---|\n")


def md5(path: Path) -> str:
    return hashlib.md5(path.read_bytes()).hexdigest()


def plan(family: str, include_review: bool = False) -> list[tuple[Path, dict]]:
    rows: list[tuple[Path, dict]] = []
    for run_id, spec in wave_g.RUNS.items():
        if spec["family"] != family or spec.get("ships") is False:
            continue
        if spec["review_only"] and not include_review:
            continue
        names = spec.get("cuts") if spec["mode"] == "sheet4" else [spec.get("out", run_id)]
        for name in names or []:
            path = wave_g.STAGE / family / f"{name}.png"
            if path.exists():
                rows.append((path, spec))
    return rows


def job_of(path: Path) -> str:
    job = path.with_name(f"{path.stem}.job.json")
    if not job.exists():
        return "-"
    import json
    return str(json.loads(job.read_text(encoding="utf-8")).get("task_id", "-"))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("families", nargs="*", default=["ships", "fx"])
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--replace", action="store_true")
    parser.add_argument("--review", action="store_true",
                        help="also ship runs marked review_only (the owner approved them)")
    args = parser.parse_args()
    families = args.families or ["ships", "fx"]

    shipped: dict[str, list[str]] = {}
    blocked = 0
    for family in families:
        rows = plan(family, include_review=args.review)
        target_dir = ASSETS / family
        print(f"--- {family}: {len(rows)} file(s) staged")
        lines: list[str] = []
        for path, spec in rows:
            target = target_dir / path.name
            if target.exists() and md5(target) != md5(path) and not args.replace:
                print(f"    SKIP {path.name}: exists in the project with different bytes "
                      f"(pass --replace to overwrite)")
                blocked += 1
                continue
            alpha = "native/recraft keyed" if spec.get("alpha") else "RGB on void, not keyed"
            lines.append(f"| `{path.name}` | `{spec.get('hull') or spec.get('out') or ''}` | "
                         f"{job_of(path)} | {alpha} | {spec['subject'].splitlines()[0][:110]}... |")
            if args.list:
                continue
            target_dir.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, target)
        if args.list:
            print(f"    (list only, {len(lines)} would ship)")
            continue
        if lines:
            log = target_dir / "generation_log_phase_g.md"
            existing = []
            if log.exists():
                existing = [ln for ln in log.read_text(encoding="utf-8").splitlines()
                            if ln.startswith("|") and not ln.startswith("|---")
                            and not ln.startswith("| File")]
            merged: list[str] = []
            for row in lines + existing:
                name = row.split("`")[1] if "`" in row else row
                if name not in [r.split("`")[1] for r in merged if "`" in r]:
                    merged.append(row)
            log.write_text(LOG_HEAD + "\n".join(merged) + "\n", encoding="utf-8")
            print(f"    shipped {len(lines)} file(s); log {log.relative_to(ROOT)} "
                  f"({len(merged)} rows)")
        shipped[family] = lines
    if blocked:
        print(f"{blocked} file(s) refused")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
