extends Node
## Scene routes, the overlay stack and the shared live theme.
## Screens declare intent; only the Router transitions. Contract: sections 3.4-3.6, 3.12, MENU_FLOW section 2.

signal screen_changed(route: StringName)
signal overlay_pushed(route: StringName)
signal overlay_popped(route: StringName)

const Paths := preload("res://ui/paths.gd")

const OVERLAY_LAYER_INDEX := 20
const FADE_LAYER_INDEX := 100
const FADE_SECONDS := 0.2
const BASE_FONT_SIZE := 14
const SETTLE_FRAME_LIMIT := 16

## Every font-size item the baked theme pins per type. Per-type items take
## precedence over Theme.default_font_size, so ui_scale has to be applied to all
## of them or the setting stays invisible (IMPLEMENTATION_PLAN section 3.6).
## The theme side is generated by tools/build_theme.gd: every set_font_size() call
## there needs a matching entry here, or that item stops following ui_scale.
const FONT_SIZE_ITEMS: Array[Dictionary] = [
	{&"type": &"Label", &"item": &"font_size"},
	{&"type": &"Button", &"item": &"font_size"},
	{&"type": &"LineEdit", &"item": &"font_size"},
	{&"type": &"OptionButton", &"item": &"font_size"},
	{&"type": &"PopupMenu", &"item": &"font_size"},
	{&"type": &"RichTextLabel", &"item": &"normal_font_size"},
	{&"type": &"RichTextLabel", &"item": &"bold_font_size"},
	{&"type": &"RichTextLabel", &"item": &"italics_font_size"},
	{&"type": &"RichTextLabel", &"item": &"bold_italics_font_size"},
	{&"type": &"RichTextLabel", &"item": &"mono_font_size"},
	{&"type": &"TooltipLabel", &"item": &"font_size"},
	{&"type": &"TabContainer", &"item": &"font_size"},
	{&"type": &"TabBar", &"item": &"font_size"},
	{&"type": &"ScreenTitle", &"item": &"font_size"},
	{&"type": &"SectionHeader", &"item": &"font_size"},
	{&"type": &"HudReadout", &"item": &"font_size"},
	{&"type": &"MenuButton", &"item": &"font_size"},
	{&"type": &"MenuButtonPlate", &"item": &"font_size"},
	{&"type": &"DialogTitle", &"item": &"font_size"},
	{&"type": &"Version", &"item": &"font_size"},
	{&"type": &"SlotNumber", &"item": &"font_size"},
	{&"type": &"HeroTitle", &"item": &"font_size"},
	{&"type": &"StationButton", &"item": &"font_size"},
	{&"type": &"StationPanelTitle", &"item": &"font_size"},
	{&"type": &"StationValue", &"item": &"font_size"},
	{&"type": &"StationCaption", &"item": &"font_size"},
	{&"type": &"FlavourText", &"item": &"font_size"},
	{&"type": &"ItemList", &"item": &"font_size"},
]

var _overlay_layer: CanvasLayer
var _fade_layer: CanvasLayer
var _fade_rect: ColorRect
var _overlays: Array[Dictionary] = []
var _route: StringName = &""
var _busy := false
var _theme_cache: Theme = null
var _theme_source: Theme = null
var _base_font_size := BASE_FONT_SIZE
var _tween: Tween = null


func _ready() -> void:
	_overlay_layer = _make_layer(&"OverlayLayer", OVERLAY_LAYER_INDEX)
	_fade_layer = _make_layer(&"FadeLayer", FADE_LAYER_INDEX)
	_fade_rect = ColorRect.new()
	_fade_rect.name = &"Fade"
	_fade_rect.set_anchors_preset(Control.PRESET_FULL_RECT)
	_fade_rect.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_fade_rect.color = _themed_fade_colour(0.0)
	_fade_layer.add_child(_fade_rect)
	_connect_settings()
	_bind_entry_scene.call_deferred()


func _exit_tree() -> void:
	if _tween != null and _tween.is_valid():
		_tween.kill()


func route(route_name: StringName, params: Dictionary = {}) -> void:
	if _busy:
		return
	if not Paths.route_exists(route_name):
		push_warning("Router: no scene is available for route '%s'" % route_name)
		return
	var packed := load(Paths.route_path(route_name)) as PackedScene
	if packed == null:
		push_warning("Router: route '%s' is not a PackedScene" % route_name)
		return
	_busy = true
	_fade_rect.mouse_filter = Control.MOUSE_FILTER_STOP
	await _fade_to(1.0).finished
	var previous_name := _current_scene_name()
	get_tree().change_scene_to_packed(packed)
	var root := await _await_scene(previous_name)
	_route = route_name
	if root is Control:
		(root as Control).theme = live_theme()
	_bind_intents(root)
	if root != null and root.has_method(&"on_route"):
		root.call(&"on_route", params)
	screen_changed.emit(route_name)
	await _fade_to(0.0).finished
	_fade_rect.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_busy = false


func push_overlay(route_name: StringName, params: Dictionary = {}) -> void:
	if _busy or _find_overlay(route_name) != null:
		return
	if not Paths.route_exists(route_name):
		push_warning("Router: no scene is available for overlay '%s'" % route_name)
		return
	var packed := load(Paths.route_path(route_name)) as PackedScene
	if packed == null:
		push_warning("Router: overlay '%s' is not a PackedScene" % route_name)
		return
	var instance := packed.instantiate()
	if instance == null:
		return
	if instance is Control:
		(instance as Control).theme = live_theme()
	# Captured before the overlay enters the tree: an overlay that grabs focus in
	# its own _ready() would otherwise become its own opener.
	var opener := _focus_weakref()
	_overlay_layer.add_child(instance)
	_bind_intents(instance)
	if instance.has_method(&"on_route"):
		instance.call(&"on_route", params)
	_overlays.append({&"route": route_name, &"node": instance, &"opener": opener})
	overlay_pushed.emit(route_name)


func pop_overlay() -> void:
	_pop_entries(1)


func current_route() -> StringName:
	return _route


func overlay_depth() -> int:
	return _overlays.size()


func is_busy() -> bool:
	return _busy


func live_theme() -> Theme:
	if _theme_cache == null:
		_theme_source = load(Paths.THEME) as Theme
		_theme_cache = _theme_source.duplicate() if _theme_source != null else Theme.new()
		_base_font_size = _theme_cache.default_font_size if _theme_cache.default_font_size > 0 else BASE_FONT_SIZE
	_scale_font_sizes()
	return _theme_cache


func request_quit() -> void:
	get_tree().quit()


func _make_layer(layer_name: StringName, layer_index: int) -> CanvasLayer:
	var layer := CanvasLayer.new()
	layer.name = layer_name
	layer.layer = layer_index
	add_child(layer)
	return layer


func _fade_to(alpha: float) -> Tween:
	_fade_rect.color = _themed_fade_colour(_fade_rect.color.a)
	if _tween != null and _tween.is_valid():
		_tween.kill()
	_tween = create_tween()
	_tween.tween_property(_fade_rect, "color:a", alpha, FADE_SECONDS)
	return _tween


func _themed_fade_colour(alpha: float) -> Color:
	var theme := live_theme()
	var base := theme.get_color(&"void_fade", &"Tokens") if theme.has_color(&"void_fade", &"Tokens") else Color.BLACK
	return Color(base.r, base.g, base.b, alpha)


func _current_scene_name() -> StringName:
	var scene := get_tree().current_scene
	return scene.name if scene != null else &""


func _await_scene(previous_name: StringName) -> Node:
	for i in SETTLE_FRAME_LIMIT:
		await get_tree().process_frame
		var scene := get_tree().current_scene
		if scene != null and scene.name != previous_name:
			return scene
	return get_tree().current_scene


func _bind_entry_scene() -> void:
	## The entry scene is never routed *to*, so nothing else would bind its intent signals.
	var entry := get_tree().current_scene
	if entry == null:
		return
	if entry is Control:
		(entry as Control).theme = live_theme()
	_bind_intents(entry)
	_route = _route_for_scene(entry)


func _route_for_scene(scene: Node) -> StringName:
	var scene_path := scene.scene_file_path
	if scene_path.is_empty():
		return &""
	for route_name: StringName in Paths.ROUTES:
		if Paths.ROUTES[route_name] == scene_path:
			return route_name
	return &""


func _bind_intents(node: Node) -> void:
	if node == null:
		return
	if node.has_signal(&"route_requested") and not node.is_connected(&"route_requested", _on_route_requested):
		node.connect(&"route_requested", _on_route_requested)
	if node.has_signal(&"overlay_requested"):
		node.connect(&"overlay_requested", _on_overlay_requested.bind(node))
	if node.has_signal(&"overlay_close_requested"):
		node.connect(&"overlay_close_requested", _on_overlay_close_requested.bind(node))


func _on_route_requested(route_name: StringName, params: Dictionary) -> void:
	route(route_name, params)


func _on_overlay_requested(route_name: StringName, params: Dictionary, _source: Node) -> void:
	push_overlay(route_name, params)


func _on_overlay_close_requested(source: Node) -> void:
	_pop_source(source)


func _pop_source(source: Node) -> void:
	var depth := _index_of(source)
	if depth < 0:
		return
	_pop_entries(_overlays.size() - depth)


func _pop_entries(count: int) -> void:
	for i in mini(count, _overlays.size()):
		var entry: Dictionary = _overlays.pop_back()
		var tracked: Variant = entry[&"node"]
		if tracked != null and is_instance_valid(tracked):
			(tracked as Node).queue_free()
		_restore_focus(entry[&"opener"])
		overlay_popped.emit(entry[&"route"])


func _find_overlay(route_name: StringName) -> Node:
	for entry: Dictionary in _overlays:
		if entry[&"route"] == route_name:
			var tracked: Variant = entry[&"node"]
			if is_instance_valid(tracked):
				return tracked as Node
	return null


func _index_of(node: Node) -> int:
	for i in _overlays.size():
		if _overlays[i][&"node"] == node:
			return i
	return -1


func _focus_weakref() -> WeakRef:
	var viewport := get_viewport()
	if viewport == null:
		return null
	var focus_owner := viewport.gui_get_focus_owner()
	if focus_owner == null:
		return null
	return weakref(focus_owner)


func _restore_focus(reference: Variant) -> void:
	if not reference is WeakRef:
		return
	var opener: Variant = (reference as WeakRef).get_ref()
	if is_instance_valid(opener) and opener is Control and (opener as Control).is_inside_tree():
		(opener as Control).grab_focus()


func _connect_settings() -> void:
	var settings := _service(&"SettingsManager")
	if settings == null or not settings.has_signal(&"setting_changed"):
		return
	if not settings.is_connected(&"setting_changed", _on_setting_changed):
		settings.connect(&"setting_changed", _on_setting_changed)


func _on_setting_changed(section: StringName, key: StringName, _value: Variant) -> void:
	if section == &"interface" and key == &"ui_scale" and _theme_cache != null:
		_scale_font_sizes()


func _scale_font_sizes() -> void:
	## Bases are read back from the source theme on every call, so repeated scale
	## changes never compound.
	var scale: float = _requested_ui_scale()
	if _theme_cache == null:
		return
	_theme_cache.default_font_size = roundi(float(_base_font_size) * scale)
	if _theme_source == null:
		return
	for entry: Dictionary in FONT_SIZE_ITEMS:
		var type: StringName = entry[&"type"]
		var item: StringName = entry[&"item"]
		if not _theme_source.has_font_size(item, type):
			continue
		var base: int = _theme_source.get_font_size(item, type)
		_theme_cache.set_font_size(item, type, roundi(float(base) * scale))


func _requested_ui_scale() -> float:
	var settings := _service(&"SettingsManager")
	if settings == null or not settings.has_method(&"ui_scale"):
		return 1.0
	return float(settings.call(&"ui_scale"))


func _service(service_name: StringName) -> Node:
	## Autoload names are not resolvable identifiers until the project patch lands
	## (project.godot is applied by the orchestrator), so services are looked up by name.
	if not is_inside_tree():
		return null
	return get_tree().root.get_node_or_null(NodePath(service_name))
